export const CHAIN_SPECIFIC_INTENTS: Record<string, string[]> = {
  // Celo Alfajores examples
  "44787": [
    "Check my CELO balance",
    "What's my USDC balance?",
    "Transfer 5 CELO",
    "Send 10 USDC",
    "Approve 100 USDC",
    "Authorize spender to use 50 CELO",
    "What's my allowance for USDC?",
    "Check how much CELO I've approved",
    "What's the total supply of CELO?",
    "Show me the total supply of USDC on Celo",
    "Convert 1 CELO to base units",
    "Convert 1000000000000000000 CELO from base units to human readable",
  ],
  // Rootstock examples
  "31": [
    "Check my RBTC balance",
    "What's my USDT balance on Rootstock?",
    "Transfer 0.01 RBTC",
    "Send 5 USDT",
    "Approve 10 USDT",
    "Authorize spender to use 0.5 RBTC",
    "What's my allowance for USDT?",
    "Check how much RBTC I've approved",
    "What's the total supply of RBTC?",
    "Show me the total supply of USDT on Rootstock",
    "Convert 0.1 RBTC to base units",
    "Convert 100000000000000000 RBTC from base units to human readable",
  ],
  // Saga IFI examples
  "2743859179913000": [
    "Check my IFI balance",
    "What's my USDC balance on Saga?",
    "Transfer 10 IFI",
    "Send 5 USDC",
    "Approve 50 IFI",
    "Authorize spender to use 20 USDC",
    "What's my allowance for IFI?",
    "Check how much USDC I've approved",
    "What's the total supply of IFI?",
    "Show me the total supply of USDC on Saga",
    "Convert 100 IFI to base units",
    "Convert 50000000000000000000 IFI from base units to human readable",
  ],
  // Default examples for any other chain
  default: [
    "Check my token balance",
    "What's my ETH balance?",
    "Transfer 0.1 ETH",
    "Send 100 USDC",
    "Approve 1000 USDC",
    "Authorize spender to use 10 ETH",
    "What's my allowance for USDC?",
    "Check how much ETH I've approved",
    "What's the total supply of ETH?",
    "Show me the total supply of USDC",
    "Convert 1 ETH to base units",
    "Convert 1000000000000000000 ETH from base units to human readable",
  ],
};
